// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jbchorg.Models;

namespace jbchorg.Migrations
{
    [DbContext(typeof(JbchorgDBContext))]
    [Migration("20181102051413_star")]
    partial class star
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("jbchorg.Models.Asociado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AMaterno");

                    b.Property<string>("APaterno");

                    b.Property<string>("Area");

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("GAcademico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("TAsociado");

                    b.HasKey("Id");

                    b.ToTable("Asociado");
                });

            modelBuilder.Entity("jbchorg.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AMaterno");

                    b.Property<string>("APaterno");

                    b.Property<string>("Asunto");

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Movil");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("jbchorg.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("ID");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
